// Code generated by protoc-gen-go. DO NOT EDIT.
// source: executor.proto

package executor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandStatus int32

const (
	CommandStatus_UNKNOWN     CommandStatus = 0
	CommandStatus_IN_QUEUE    CommandStatus = 1
	CommandStatus_IN_PROGRESS CommandStatus = 2
	CommandStatus_COMPLETE    CommandStatus = 3
)

var CommandStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "IN_QUEUE",
	2: "IN_PROGRESS",
	3: "COMPLETE",
}

var CommandStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"IN_QUEUE":    1,
	"IN_PROGRESS": 2,
	"COMPLETE":    3,
}

func (x CommandStatus) String() string {
	return proto.EnumName(CommandStatus_name, int32(x))
}

func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{0}
}

type Command struct {
	Binary               string   `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	Parameters           []string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetBinary() string {
	if m != nil {
		return m.Binary
	}
	return ""
}

func (m *Command) GetParameters() []string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type ExecuteRequest struct {
	Command              *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{1}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type ExecuteResponse struct {
	TimeTakenInMillis    int64         `protobuf:"varint,1,opt,name=time_taken_in_millis,json=timeTakenInMillis,proto3" json:"time_taken_in_millis,omitempty"`
	CommandOutput        string        `protobuf:"bytes,2,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	Status               CommandStatus `protobuf:"varint,3,opt,name=status,proto3,enum=executor.CommandStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{2}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

func (m *ExecuteResponse) GetTimeTakenInMillis() int64 {
	if m != nil {
		return m.TimeTakenInMillis
	}
	return 0
}

func (m *ExecuteResponse) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

func (m *ExecuteResponse) GetStatus() CommandStatus {
	if m != nil {
		return m.Status
	}
	return CommandStatus_UNKNOWN
}

func init() {
	proto.RegisterEnum("executor.CommandStatus", CommandStatus_name, CommandStatus_value)
	proto.RegisterType((*Command)(nil), "executor.Command")
	proto.RegisterType((*ExecuteRequest)(nil), "executor.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "executor.ExecuteResponse")
}

func init() { proto.RegisterFile("executor.proto", fileDescriptor_12d1cdcda51e000f) }

var fileDescriptor_12d1cdcda51e000f = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x5f, 0x4b, 0xfa, 0x60,
	0x14, 0xc7, 0x9d, 0x03, 0xa7, 0x47, 0x9d, 0xf3, 0xe1, 0xc7, 0xaf, 0xd5, 0x45, 0xc8, 0x20, 0x90,
	0x02, 0x05, 0xbb, 0x0e, 0x0a, 0x19, 0x31, 0xca, 0x4d, 0x9f, 0x29, 0x5d, 0x8e, 0x69, 0xe7, 0x62,
	0xe4, 0xfe, 0xf4, 0xfc, 0x89, 0x7a, 0x2b, 0xbd, 0xda, 0xf0, 0x71, 0x6a, 0x52, 0x77, 0x5d, 0x9e,
	0xf3, 0x39, 0xfb, 0xec, 0x7c, 0x0f, 0x0f, 0x98, 0xf8, 0x8e, 0x2b, 0x29, 0x72, 0x36, 0x28, 0x58,
	0x2e, 0x72, 0x52, 0xdf, 0xd5, 0xce, 0x1d, 0x18, 0xe3, 0x3c, 0x4d, 0xe3, 0xec, 0x99, 0xfc, 0x87,
	0xda, 0x32, 0xc9, 0x62, 0xf6, 0x61, 0x6b, 0x3d, 0xad, 0xdf, 0xa0, 0x65, 0x45, 0xce, 0x01, 0x8a,
	0x98, 0xc5, 0x29, 0x0a, 0x64, 0xdc, 0xae, 0xf6, 0xf4, 0x7e, 0x83, 0x7e, 0xeb, 0x38, 0x37, 0x60,
	0xba, 0x4a, 0x87, 0x14, 0x5f, 0x25, 0x72, 0x41, 0xae, 0xc0, 0x58, 0x6d, 0xa5, 0x4a, 0xd5, 0x1c,
	0x75, 0x07, 0xfb, 0x05, 0xca, 0xbf, 0xd1, 0xdd, 0x84, 0xf3, 0xa9, 0x41, 0x67, 0xff, 0x3d, 0x2f,
	0xf2, 0x8c, 0x23, 0x19, 0xc2, 0x3f, 0x91, 0xa4, 0x18, 0x89, 0xf8, 0x05, 0xb3, 0x28, 0xc9, 0xa2,
	0x34, 0x59, 0xaf, 0x13, 0xae, 0x6c, 0x3a, 0xed, 0x6e, 0xd8, 0x7c, 0x83, 0xbc, 0x6c, 0xa2, 0x00,
	0xb9, 0x00, 0xb3, 0xf4, 0x45, 0xb9, 0x14, 0x85, 0x14, 0x76, 0x55, 0x65, 0x68, 0x97, 0xdd, 0x40,
	0x35, 0xc9, 0x10, 0x6a, 0x5c, 0xc4, 0x42, 0x72, 0x5b, 0xef, 0x69, 0x7d, 0x73, 0x74, 0xf2, 0x63,
	0xaf, 0x50, 0x61, 0x5a, 0x8e, 0x5d, 0x7a, 0xd0, 0x3e, 0x02, 0xa4, 0x09, 0xc6, 0xc2, 0x7f, 0xf0,
	0x83, 0x27, 0xdf, 0xaa, 0x90, 0x16, 0xd4, 0x3d, 0x3f, 0x9a, 0x2d, 0xdc, 0x85, 0x6b, 0x69, 0xa4,
	0x03, 0x4d, 0xcf, 0x8f, 0xa6, 0x34, 0xb8, 0xa7, 0x6e, 0x18, 0x5a, 0xd5, 0x0d, 0x1e, 0x07, 0x93,
	0xe9, 0xa3, 0x3b, 0x77, 0x2d, 0x7d, 0x74, 0xc8, 0x99, 0xb3, 0x10, 0xd9, 0x5b, 0xb2, 0x42, 0x72,
	0x0b, 0x46, 0x19, 0x9d, 0xd8, 0x87, 0x55, 0x8e, 0xaf, 0x79, 0x76, 0xfa, 0x0b, 0xd9, 0xde, 0xc9,
	0xa9, 0x10, 0x17, 0x5a, 0x33, 0x89, 0x12, 0xff, 0xa6, 0x59, 0xd6, 0xd4, 0xbb, 0xb8, 0xfe, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0xf3, 0xfd, 0x79, 0x73, 0x29, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExecutorServiceClient is the client API for ExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecutorServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	QueueExecute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type executorServiceClient struct {
	cc *grpc.ClientConn
}

func NewExecutorServiceClient(cc *grpc.ClientConn) ExecutorServiceClient {
	return &executorServiceClient{cc}
}

func (c *executorServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/executor.ExecutorService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) QueueExecute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/executor.ExecutorService/QueueExecute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutorServiceServer is the server API for ExecutorService service.
type ExecutorServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	QueueExecute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

func RegisterExecutorServiceServer(s *grpc.Server, srv ExecutorServiceServer) {
	s.RegisterService(&_ExecutorService_serviceDesc, srv)
}

func _ExecutorService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/executor.ExecutorService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_QueueExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).QueueExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/executor.ExecutorService/QueueExecute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).QueueExecute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecutorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "executor.ExecutorService",
	HandlerType: (*ExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _ExecutorService_Execute_Handler,
		},
		{
			MethodName: "QueueExecute",
			Handler:    _ExecutorService_QueueExecute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "executor.proto",
}
